name: Automated Tests

on: pull_request

jobs:
  tests:
    name: 'Vitest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: mv .env.example .env
      - run: bun install --frozen-lockfile
      - run: bun run test
